#!/bin/bash

# This is suuuuper specific to my current company's workflow.
_git_deployed_ref ()
{
  git fetch

  local GREPSTR="^"
  GREPSTR+=$1
  GREPSTR+="-\d\+"

  git tag | grep $GREPSTR | sort -d -r | awk 'NR==1;'
}

_git_deployed_ref $1
