#!/bin/bash

# This is suuuuper specific to my current company's workflow.
_git_deployed_ref ()
{
  git fetch &> /dev/null

  local GREPSTR="^"
  GREPSTR+=$1
  GREPSTR+="-\d\+"

  local TAG=$(git tag | grep $GREPSTR | sort -d -r | awk 'NR==1;')
  git rev-parse --verify $TAG
}

_git_deployed_ref $1
